### ISSUE TITLE
Question: Is there something like jsonpath?

### ISSUE THREAD

**Issue by rgl** [sdispater/tomlkit#133]
Is something alike jsonpath/xpath supported by this library?

Something that would allow me to get/set the value of `plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options.SystemdCgroup` that is inside the document:

```toml
version = 2
[plugins]
  [plugins."io.containerd.grpc.v1.cri"]
   [plugins."io.containerd.grpc.v1.cri".containerd]
      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
          runtime_type = "io.containerd.runc.v2"
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
            SystemdCgroup = true
```

Or something that would take `plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options` and would return the table container?
