### ISSUE TITLE
style not preserved when modifying dict

### ISSUE THREAD

**Issue by virtuald** [sdispater/tomlkit#170]
First off, thanks for this library. A style-preserving writer is a really useful and rare thing. Here's my config:

```toml
[versions]
robotpy-wpiutil             = "2022.2.1.1"
pyntcore                    = "2022.2.1.1"
robotpy-hal                 = "2022.2.1.1"
robotpy-wpimath             = "2022.2.1.2"
wpilib                      = "2022.2.1.3"
robotpy-halsim-gui          = "2022.2.1.0"
robotpy-halsim-ds-socket    = "2022.2.1.0"
robotpy-halsim-ws           = "2022.2.1.0"
robotpy-commands-v1         = "2022.2.1.1"
robotpy-commands-v2         = "2022.2.1.1"


```

When I run

```python
import tomlkit

with open("cfg.toml") as fp:
    cfgdata = tomlkit.parse(fp.read())

cfgdata["versions"]["robotpy-wpimath"] = "2022.2.1.4"
print(tomlkit.dumps(cfgdata))
```

The output is

```toml
[versions]
robotpy-wpiutil             = "2022.2.1.1"
pyntcore                    = "2022.2.1.1"
robotpy-hal                 = "2022.2.1.1"
robotpy-wpimath = "2022.2.1.4"
wpilib                      = "2022.2.1.3"
robotpy-halsim-gui          = "2022.2.1.0"
robotpy-halsim-ds-socket    = "2022.2.1.0"
robotpy-halsim-ws           = "2022.2.1.0"
robotpy-commands-v1         = "2022.2.1.1"
robotpy-commands-v2         = "2022.2.1.1"
```
For now, my workaround is to directly assign the _value, and the style information is retained:

```python
import tomlkit

with open("cfg.toml") as fp:
    cfgdata = tomlkit.parse(fp.read())

cfgdata["versions"]["robotpy-wpimath"]._value = "2022.2.1.4"
print(tomlkit.dumps(cfgdata))
```

Is this intended behavior, or am I missing something? From reading the quickstart, it seemed to me that just assigning the dictionary would keep style information, but that doesn't seem to be the case.
