### ISSUE TITLE
Commas are sometimes appended to comments

### ISSUE THREAD

**Issue by dranjan** [sdispater/tomlkit#181]
Here's a simple repro:
```python
import tomlkit

doc_str = """
[A]
B = [
    # Here's a comment.
    "C",
]
"""

doc = tomlkit.parse(doc_str)
deps = doc['A']['B'].multiline(True)
deps.append('D')
print(doc.as_string())
```
This is the output:
```toml

[A]
B = [
    # Here's a comment.,
    "C",
    "D",
]

```
The "Here's a comment" comment has a comma appended to it. (Expected behavior: exactly the same output, but without the comma appended to the comment.)
