### ISSUE TITLE
Deleting a table creates invalid output

### ISSUE THREAD

**Issue by codejedi365** [sdispater/tomlkit#204]
As specified on the [`quickstart.rst`](https://github.com/sdispater/tomlkit/blob/master/docs/quickstart.rst), one can use the `del` command to remove a table from a `TOMLDocument`.  This has a faulty implementation when dealing with multi-tier tables.  The internal data is deleted and the JSON result is as expected but the TOMLDocument will not render correctly afterword.  The resulting TOML does not combine keys and will create 2 tables with the same name which causes TOML Parser Errors on re-read.  The bug is more obscure than I first thought as it will not render 2 table headings if the immediate parent/previous table header is the same.  However, if the previous table is not the same section, it will re-render the header rather than checking the entire `TOMLDocument` for the parent header.

### Example

The example is here to illustrate an incorrect result and not for debate on if this should be done or not.

Imported `pyproject.toml`
```toml
[project]
name = "examplepkg"

[build-system]
requires = [
    "setuptools",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
dev = [
    "python-semantic-release"
]
```

Example code which creates invalid output
```python
"""Script to strip optional-dependencies from pyproject configuration."""
import json, tomlkit

with open('pyproject.toml', 'rb') as fd:
    conf = tomlkit.load(fd)

if conf.get('project', {}).get('optional-dependencies', None) is not None:
    del conf['project']['optional-dependencies']

print(json.dumps(conf, indent=2))
tomlstr = tomlkit.dumps(conf)
print(tomlstr)

# attempt reloading
prod_conf = tomlkit.loads(tomlstr)
# Raises tomlkit.exceptions.KeyAlreadyPresent: Key "project" already exists.
```

### Expected Result

JSON output (expected)

```json
{
  "project": {
    "name": "exampleprj"
  },
  "build-system": {
    "requires": [
      "setuptools",
      "wheel"
    ],
    "build-backend": "setuptools.build_meta"
  }
}
```

TOML output (expected)

```toml
[project]
name = "examplepkg"

[build-system]
requires = [
    "setuptools",
    "wheel"
]
build-backend = "setuptools.build_meta"
```

### Actual Result

JSON output (actual)
**Result: Matches Expected Result**

TOML output (actual)
**Result: Failure**

```toml
[project]
name = "examplepkg"

[build-system]
requires = [
    "setuptools",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
```
As you can see the toml generated actually outputs 2 `[project]` sections as it dropped the tiered section and the internals but the result causes the `pyproject.toml` to be invalid because of 2 defined project sections.
