### ISSUE TITLE
Unwrap doesn't unwrap contents of array

### ISSUE THREAD

**Issue by GCBallesteros** [sdispater/tomlkit#249]
I'm using `unwrap` to bring it all back to plain Python but after unwrapping elements inside an array are still of type `Container`.

Find below a minimal example to reproduce:

```toml
# minimal.toml
[a]
img_file = "asdf"
frames = [
    {foo=2},
    {foo=3},
]

[a.something]
id = "hello"
```

First I parse it:
```python
with open("minimal.toml") as fh:
    meta = tomlkit.parse(fh.read()).unwrap()
```

then I inspect the type of different parts of the output dict:
```
>>> type(meta)
<class 'dict'>
>>> type(meta["a"]["something"])
<class 'dict'>
>>> type(meta["a"]["frames"])
<class 'list'>
>>> type(meta["a"]["frames"][0])
<class 'tomlkit.container.Container'>  <----- not unwrapped
```

This behaviour is shown by tomlkit version `0.11.6` running with Python 3.9.7
