### ISSUE TITLE
Reassign the value of an outline table, the table becomes messy.

### ISSUE THREAD

**Issue by frostming** [sdispater/tomlkit#29]
## Issue
Given this file:
```toml
[site.user]
name = "John"
```
Then re-assign the table to be a string:
```python
parsed = tomlkit.parse(open("my.toml").read())
parsed['site']['user']="Tom"
print(parsed.as_string())
```
gives:
```toml
user = "Tom"
```
The table header is missing!
tomlkit version: v0.5.1

## Workaround
One needs to reassign the parent:
```python
v = parsed['site']
parsed['site'] = v.copy()
parsed['site']['user']="Tom"
print(parsed.as_string())
```
```toml
[site]
user = "Tom"
```
