### ISSUE TITLE
Convert an table to inline table, the comment is preserved unexpectedly

### ISSUE THREAD

**Issue by frostming** [sdispater/tomlkit#30]
Suppose we have following toml:
```toml
[site.user]
name = "John"  # Inline comment
age = 28
```
I want to convert `site.user` to an inline table:
```python
v = parsed['site']['user']
table = tomlkit.inline_table()
table.update(v)
print(table.as_string())
```
```toml
{age = 21,name = "John"# Inline comment}
```
What is weird is that even with:
```python
table.update(dict(v))
```
The bug still exists.

The expected behavior should be dropping all comments of original table.
