### ISSUE TITLE
Can't set value if sections out of order

### ISSUE THREAD

**Issue by MrGreenTea** [sdispater/tomlkit#64]
I stumbled upon this when `poetry version` would not update the `pyproject.toml`. 

This is the smallest example with which I can reproduce this on master:

```toml
# tests/examples/out_of_order_write.toml
[a.a]
key = "value"

[a.b]

[a.a.a]
```
```python
def test_write_nested_array(example):
    doc = loads(example("out_of_order_write"))
    doc["a"]["a"]["key"] = "new_value"
    assert doc["a"]["a"]["key"] == "new_value"
```

The test succeeds when changing the order in the example document to
```toml
[a.a]
key = "value"

[a.a.a]

[a.b]
```
