### ISSUE TITLE
Comment before table causes next entry to be in table

### ISSUE THREAD

**Issue by jpyams** [sdispater/tomlkit#98]
# Steps to Reproduce
In a tomlkit document, add a comment, a table, then a separate entry.  Dump the document to TOML.

```python
import tomlkit

doc = tomlkit.document()
doc.add(tomlkit.comment('Comment'))
doc['foo'] = {'name': 'test'}
doc['bar'] = 1
print(tomlkit.dumps(doc))
```

# Expected result
`bar` is outside the table.

```toml
bar = 1
# Comment

[foo]
name = "test"
```

# Actual result
`bar` is dumped as an entry in `foo`.

```toml
# Comment

[foo]
name = "test"
bar = 1
```

# Additional notes

This behavior only happens with the first key after the table.  Subsequent entries are correctly outside the table, though after the comment.

```python
import tomlkit

doc = tomlkit.document()
doc.add(tomlkit.comment('Comment'))
doc['foo'] = {'name': 'test'}
doc['bar'] = 1
doc['baz'] = 1
print(tomlkit.dumps(doc))
```

gives

```toml
# Comment
baz = 1

[foo]
name = "test"
bar = 1
```

**Comment by jpyams** [comment]
Funny how rereading the README can make life easier.  It looks like when adding a comment tomlkit is expecting me to do

```python
import tomlkit

doc = tomlkit.document()
doc['foo'] = {'name': 'test'}
doc['foo'].comment('Comment')
doc['bar'] = 1
print(tomlkit.dumps(doc))
```

That gives me

```toml
bar = 1
[foo] # Comment
name = "test"


```

Adding the comment directly to the item also feels a lot more intuitive, so I like this more than what I was doing before.

I'm leaving this issue open because I don't know if what I was doing before is expected to work or not.  If what I was doing before was user error, then please go ahead and close this.
